[package]
name = "time_keepers"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
arboard = "3.3"
sha2 = "0.10.9"
